---
- name: "Install Homebrew"
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    NONINTERACTIVE: "1"
- name: "Install Homebrew packages"
  community.general.homebrew:
    name:
      - pyenv
      - ssdeep
      - sha2
      - git
      - sqlite
      - nmap
      - openssl
      - vim
      - wget
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - homebrew/cask/visual-studio-code
      - homebrew/cask/iterm2
      - homebrew/cask/db-browser-for-sqlite
      - homebrew/cask/utm
    state: present
- name: "Clone bspy"
  git:
    repo: 'https://github.com/0xFFaraday/bspy.git'
    dest: "{{ tools_directory }}/bspy"
    version: "{{ bspy_version }}"
    environment:
      GIT_TERMINAL_PROMPT: 0
- name: "Install bspy requirements"
  command:
    cmd: "pip install -r {{ tools_directory }}/bspy/requirements.txt"
- name: "Download and extract Chainsaw 2.x"
  unarchive:
    src: https://github.com/WithSecureLabs/chainsaw/releases/download/v{{ chainsaw_version }}/chainsaw_x86_64-apple-darwin.zip
    dest: "{{ tools_directory }}/chainsaw2"
    remote_src: true
- name: "Disable quarantine bit on Chainsaw executable"
  command:
    cmd: xattr -dr com.apple.quarantine {{ tools_directory }}/chainsaw2/chainsaw
