---
- name: "Create Tools folders"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '760'
  loop:
    - "{{ tools_directory }}"
    - "{{ tools_directory }}/chainsaw2"
    - "{{ tools_directory }}/bspy"
- name: "Install Homebrew"
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    NONINTERACTIVE: "1"
- name: "Install Homebrew packages"
  community.general.homebrew:
    name:
      - pyenv
      - ssdeep
      - sha2
      - git
      - sqlite
      - nmap
      - openssl
      - vim
      - wget
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - homebrew/cask/visual-studio-code
      - homebrew/cask/iterm2
      - homebrew/cask/db-browser-for-sqlite
      - homebrew/cask/utm
      - homebrew/cask/vmware-fusion
    state: present
- name: "Clone bspy"
  ansible.builtin.git:
    repo: 'https://github.com/0xFFaraday/bspy.git'
    dest: "{{ tools_directory }}/bspy"
    version: "{{ bspy_version }}"
- name: "Install bspy requirements"
  ansible.builtin.command:
    cmd: "pip install -r {{ tools_directory }}/bspy/requirements.txt"
- name: "Download and extract Chainsaw 2.x"
  ansible.builtin.unarchive:
    src: https://github.com/WithSecureLabs/chainsaw/releases/download/v{{ chainsaw_version }}/chainsaw_x86_64-apple-darwin.zip
    dest: "{{ tools_directory }}/chainsaw2"
    remote_src: true
- name: "Disable quarantine bit on Chainsaw executable"
  ansible.builtin.command:
    cmd: xattr -dr com.apple.quarantine {{ tools_directory }}/chainsaw2/chainsaw
- name: "Clone Chainsaw hunting rules"
  ansible.builtin.git:
    repo: 'https://github.com/import-pandas-as-numpy/chainsaw-rules'
    dest: "{{ tools_directory }}/chainsaw2/chainsaw-rules"
